package budjetointisovellus.domain;

/**
 *
 * Luetellut tyypit kulun kategorialle
 */
public enum Category {
    ASIOINTIKULUT, SUUNNITTELU, TONTTI, TYOMAAHANKINNAT, MAARAKENNUS, 
    PERUSTUKSETJAALAPOHJA, TALOPAKETTI, ULKOSEINARAKENTEET, 
    VALIJAYLAPOHJARAKENTEET, VESIKATTORAKENTEET, JULKISIVUPINNOITTEET, 
    OVETJAIKKUNAT, SISASEINAT, SISAKATTO, SISAPINNOITTEET, HORMITJATULISIJAT, 
    LATTIA, KIINTOKALUSTEET, VALIOVET, PORTAAT, LISTAT, KODINKONEET, LAMMITYS, 
    PUTKITYOT, ILMANVAIHTO, SAHKOTYOT, PIHATYOT, TERASSI, MUUT
}