package budjetointisovellus.domain;

/**
 *
 * Luetellut tyypit kulun kategorialle
 */
public enum Category {
    ASIOINTIKULUT, SUUNNITTELU, TYOMAAHANKINNAT, MAARAKENNUS, PERUSTUKSET, 
    ALAPOHJA, ULKOSEINARAKENTEET, VALIJAYLAPOHJARAKENTEET, VESIKATTORAKENTEET, 
    JULKISIVUPINNOITTEET, OVETJAIKKUNAT, SISASEINAT, SISAKATTO, 
    HORMITJATULISIJAT, LATTIA, KIINTOKALUSTEET, VALIOVET, PORTAAT, LISTAT, 
    KODINKONEET, LAMMITYS, PUTKITYOT, ILMANVAIHTO, SAHKOTYOT, MUUT
}
