package budjetointisovellus.domain;

/**
 *
 * Luetellut tyypit kulun kategorialle
 */
public enum Category {
    ASIOINTIKULUT, SUUNNITTELU, TYOMAAHANKINNAT, MAARAKENNUS, PERUSTUKSET, 
    ALAPOHJA, ULKOSEINARAKENTEET, VALIJAYLAPOHJARAKENTEET, VESIKATTORAKENTEET, 
    JULKISIVUPINNOITTEET, OVETJAIKKUNAT, SISASEINÄT, SISAKATTO, 
    HORMITJATULISIJAT, LATTIA, KIINTOKALUSTEET, VALIOVET, PORTAAT, LISTAT, 
    KODINKONEET, LAMMITYS, PUTKITYÖT, ILMANVAIHTO, SAHKOTYOT, MUUT
}
